[build]
  publish = "." # ده معناه إن ملفات الـ HTML بره
  functions = "netlify/functions" # ده مكان الباك إند

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status = 200